[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_API_URL = 'https://web-scraper-api-365.netlify.app/api'

[build.backend]
  base = "backend"
  command = "npm run build"
  functions = "build"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200